f=open('myfile.txt','w')
f.write('happy new year merry cristmas')
f.close()
f=open('myfile.txt','r')
d=f.read()
#print(d)
f.close()
f=open('myfile.txt','r+')
#print(f.read())
f.write('nice christmas eve')
#f.seek(0)
#print(f.read())
f.close()
f=open('myfile.txt','r')
print(f.read())

